AraucoAnnotations:
    resource: "@AraucoCSVBundle/Controller/StockController.php"
    type: annotation

arauco_base:
    resource: "@AraucoBaseBundle/Controller/"
    type:     annotation
    prefix:   /

arauco_csv:
    resource: "@AraucoCSVBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
