<?php

namespace Arauco\CSVBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidosRepository extends EntityRepository
{
    public function findAllTotalPedidos()
    {
        return $this->getEntityManager()->createQuery("
            SELECT p.Material, p.DescripcionMaterial, sum(p.VolPedido) Suma
            FROM AraucoCSVBundle:Pedidos p
            WHERE p.StatusMovimientodeMcia = 'A'
            GROUP By p.Material
            ")->getResult();
    }

    public function findPedidosAsig($startWeek, $endWeek, $status)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.Nro_Entrega
                AND P.PosPedido = S.Pos_Entrega
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosETA($startWeek, $endWeek, $status)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.STO_DOCENTREGA_ASI_ETA
                AND P.PosPedido = S.STO_POSPEDIDO_ASI_ETA
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosFPE($startWeek, $endWeek, $status)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.STO_DOCENTREGA_ASI_FPE
                AND P.PosPedido = S.STO_POSPEDIDO_ASI_FPE
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosAsigIncETA($startWeek, $endWeek, $status, $completable)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.Nro_Entrega
                AND P.PosPedido = S.Pos_Entrega
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.PED_COMPLETABLE_ETA ='".$completable."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosETAIncETA($startWeek, $endWeek, $status, $completable)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.STO_DOCENTREGA_ASI_ETA
                AND P.PosPedido = S.STO_POSPEDIDO_ASI_ETA
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.PED_COMPLETABLE_ETA ='".$completable."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosFPEIncETA($startWeek, $endWeek, $status, $completable)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.STO_DOCENTREGA_ASI_FPE
                AND P.PosPedido = S.STO_POSPEDIDO_ASI_FPE
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.PED_COMPLETABLE_ETA ='".$completable."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosAsigIncFPE($startWeek, $endWeek, $status, $completable)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.Nro_Entrega
                AND P.PosPedido = S.Pos_Entrega
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.PED_COMPLETABLE_FPE ='".$completable."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosETAIncFPE($startWeek, $endWeek, $status, $completable)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.STO_DOCENTREGA_ASI_ETA
                AND P.PosPedido = S.STO_POSPEDIDO_ASI_ETA
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.PED_COMPLETABLE_FPE ='".$completable."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }

    public function findPedidosFPEIncFPE($startWeek, $endWeek, $status, $completable)
    {
        return $this->getEntityManager()->createQuery("
            SELECT
                P.DocEntrega,
                P.PosPedido,
                S.Material,
                S.Desc_Mat,
                P.VolPedido,
                SUM( S.M3 ) as M3
            FROM
                AraucoCSVBundle:Pedidos P,
                AraucoCSVBundle:Stock S
            WHERE
                P.DocEntrega = S.STO_DOCENTREGA_ASI_FPE
                AND P.PosPedido = S.STO_POSPEDIDO_ASI_FPE
                AND P.Eta >='".$startWeek."'
                AND P.Eta <='".$endWeek."'
                AND P.StatusComplete = '".$status."'
                AND P.PED_COMPLETABLE_FPE ='".$completable."'
                AND P.StatusMovimientodeMcia = 'A'
            GROUP BY
                P.DocEntrega,
                P.PosPedido
            ORDER BY
                P.DocEntrega,
                P.PosPedido")->getResult();
    }
}

//Total volumen de pedidos por material
//SELECT Material, DescripcionMaterial, sum(VolPedido), StatusMovimientodeMcia
//FROM Pedidos
//WHERE StatusMovimientodeMcia IN ('A', 'C')
//GROUP BY Material, StatusMovimientodeMcia;
