<?php

namespace Arauco\CSVBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidosRepository extends EntityRepository
{
    public function findAllTotalPedidos()
    {
        return $this->getEntityManager()->createQuery("
            SELECT p.Material, p.DescripcionMaterial, sum(p.VolPedido) Suma
            FROM AraucoCSVBundle:Pedidos p
            WHERE p.StatusMovimientodeMcia = 'A'
            GROUP By p.Material
            ")->getResult();
    }
}

//Total volumen de pedidos por material
//SELECT Material, DescripcionMaterial, sum(VolPedido), StatusMovimientodeMcia
//FROM Pedidos
//WHERE StatusMovimientodeMcia IN ('A', 'C')
//GROUP BY Material, StatusMovimientodeMcia;
